// <auto-generated />
using System;
using DB.SportHive.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250424095305_EventTables")]
    partial class EventTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DB.SportHive.Domain.Athlete", b =>
                {
                    b.Property<string>("login")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Login");

                    b.Property<DateTime>("DataBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataBirth");

                    b.Property<string>("FirsName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("FirsName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("LastName");

                    b.Property<string>("TypeSport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TypeSport");

                    b.HasKey("login");

                    b.ToTable("Athlete");
                });

            modelBuilder.Entity("DB.SportHive.Domain.EMatchesAthlete", b =>
                {
                    b.Property<string>("loginAthlete")
                        .HasColumnType("character varying(40)");

                    b.Property<long>("IdExtremeMatches")
                        .HasColumnType("bigint");

                    b.HasKey("loginAthlete", "IdExtremeMatches");

                    b.HasIndex("IdExtremeMatches");

                    b.ToTable("EMatchesAthlete");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Event", b =>
                {
                    b.Property<long>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdEvent"));

                    b.Property<DateTime>("DataEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameEvent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NameEvent");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("systems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEvent");

                    b.HasIndex("IdEvent")
                        .IsUnique();

                    b.ToTable("Event");
                });

            modelBuilder.Entity("DB.SportHive.Domain.ExtremeMatch", b =>
                {
                    b.Property<long>("IdExtremeMatches")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdExtremeMatches"));

                    b.Property<string>("AddInformation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("AddInformation");

                    b.Property<DateTime>("DataMatch")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdEvent")
                        .HasColumnType("bigint");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("TimeMatch")
                        .HasColumnType("interval");

                    b.Property<int>("Tour")
                        .HasColumnType("integer")
                        .HasColumnName("Tour");

                    b.HasKey("IdExtremeMatches");

                    b.HasIndex("IdEvent");

                    b.HasIndex("LocationId");

                    b.ToTable("ExtremeMatch");
                });

            modelBuilder.Entity("DB.SportHive.Domain.IndividualMatch", b =>
                {
                    b.Property<long>("IdIndividualMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdIndividualMatch"));

                    b.Property<string>("AddInformation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("AddInformation");

                    b.Property<DateTime>("DataMatch")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdEvent")
                        .HasColumnType("bigint");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("TimeMatch")
                        .HasColumnType("interval");

                    b.Property<int>("Tour")
                        .HasColumnType("integer")
                        .HasColumnName("Tour");

                    b.Property<string>("loginFirstAthlete")
                        .IsRequired()
                        .HasColumnType("character varying(40)");

                    b.Property<string>("loginSecondAthlete")
                        .IsRequired()
                        .HasColumnType("character varying(40)");

                    b.HasKey("IdIndividualMatch");

                    b.HasIndex("IdEvent");

                    b.HasIndex("LocationId");

                    b.HasIndex("loginFirstAthlete");

                    b.HasIndex("loginSecondAthlete");

                    b.ToTable("IndividualMatch");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Judge", b =>
                {
                    b.Property<string>("login")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Login");

                    b.Property<DateTime>("DataBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataBirth");

                    b.Property<string>("FirsName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("FirsName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("LastName");

                    b.HasKey("login");

                    b.ToTable("Judge");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Organization", b =>
                {
                    b.Property<string>("login")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Login");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Country");

                    b.Property<DateTime>("DateFoundation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateFoundation");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("NameOrganization")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("NameOrganization");

                    b.Property<string>("TypeOrganozation")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("TypeOrganozation");

                    b.HasKey("login");

                    b.HasIndex("NameOrganization");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationJudge", b =>
                {
                    b.Property<string>("LoginJudge")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("LoginJudge");

                    b.Property<string>("LoginOrganization")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("LoginOrganization");

                    b.HasKey("LoginJudge", "LoginOrganization");

                    b.HasIndex("LoginOrganization");

                    b.ToTable("OrganizationJudge");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationTeam", b =>
                {
                    b.Property<string>("LoginOrganization")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("LoginOrganization");

                    b.Property<string>("NameComand")
                        .HasColumnType("text")
                        .HasColumnName("NameComand");

                    b.HasKey("LoginOrganization", "NameComand");

                    b.HasIndex("NameComand");

                    b.ToTable("OrganizationTeam");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationTrainer", b =>
                {
                    b.Property<string>("LoginOrganization")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("LoginOrganization");

                    b.Property<string>("LoginTraine")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("LoginTraine");

                    b.HasKey("LoginOrganization", "LoginTraine");

                    b.HasIndex("LoginTraine");

                    b.ToTable("OrganizationTrainer");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Team", b =>
                {
                    b.Property<string>("TeamName")
                        .HasColumnType("text")
                        .HasColumnName("TeamName");

                    b.Property<string>("LoginTrainer")
                        .IsRequired()
                        .HasColumnType("character varying(40)")
                        .HasColumnName("LoginTrainer");

                    b.Property<string>("TeamPhoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trainerlogin")
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TypeSport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TypeSport");

                    b.HasKey("TeamName");

                    b.HasIndex("LoginTrainer")
                        .IsUnique();

                    b.HasIndex("Trainerlogin");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("DB.SportHive.Domain.TeamAthlete", b =>
                {
                    b.Property<string>("NameTeam")
                        .HasColumnType("text")
                        .HasColumnName("NameTeam");

                    b.Property<string>("loginAthlets")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("IdAthlete");

                    b.Property<string>("AthleteStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdTeam")
                        .HasColumnType("integer");

                    b.HasKey("NameTeam", "loginAthlets");

                    b.HasIndex("loginAthlets");

                    b.ToTable("TeamAthlete");
                });

            modelBuilder.Entity("DB.SportHive.Domain.TeamMatch", b =>
                {
                    b.Property<long>("IdTeamMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdTeamMatch"));

                    b.Property<string>("AddInformation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("AddInformation");

                    b.Property<DateTime>("DataMatch")
                        .HasColumnType("date");

                    b.Property<long>("IdEvent")
                        .HasColumnType("bigint");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("NameFirstTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameSecondTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TimeMatch")
                        .HasColumnType("time");

                    b.Property<int>("Tour")
                        .HasColumnType("integer")
                        .HasColumnName("Tour");

                    b.HasKey("IdTeamMatch");

                    b.HasIndex("IdEvent");

                    b.HasIndex("LocationId");

                    b.HasIndex("NameFirstTeam");

                    b.HasIndex("NameSecondTeam");

                    b.ToTable("TeamMatch", (string)null);
                });

            modelBuilder.Entity("DB.SportHive.Domain.Trainer", b =>
                {
                    b.Property<string>("login")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Login");

                    b.Property<DateTime>("DataBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataBirth");

                    b.Property<string>("FirsName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("FirsName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("LastName");

                    b.HasKey("login");

                    b.ToTable("Trainer");
                });

            modelBuilder.Entity("DB.SportHive.Domain.User", b =>
                {
                    b.Property<string>("login")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("login");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mail");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("HashPassword");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Role");

                    b.Property<bool>("isEmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("EmailConfirmed");

                    b.Property<string>("refreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refreshToken");

                    b.HasKey("login");

                    b.HasIndex("login")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("DB.SportHive.Domain.UserPhoto", b =>
                {
                    b.Property<string>("login")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(40)")
                        .HasColumnName("login");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("text")
                        .HasColumnName("ProfilePhoto");

                    b.HasKey("login");

                    b.ToTable("UserPhoto");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Athlete", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Athlete", "login")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.EMatchesAthlete", b =>
                {
                    b.HasOne("DB.SportHive.Domain.ExtremeMatch", "ExtremeMatch")
                        .WithMany("MatchesAthletes")
                        .HasForeignKey("IdExtremeMatches")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Athlete", "Athlete")
                        .WithMany("MatchesAthletes")
                        .HasForeignKey("loginAthlete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("ExtremeMatch");
                });

            modelBuilder.Entity("DB.SportHive.Domain.ExtremeMatch", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Event", "Event")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DB.SportHive.Domain.IndividualMatch", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Event", "Event")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Athlete", "FirstAthlete")
                        .WithMany()
                        .HasForeignKey("loginFirstAthlete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Athlete", "SecondAthlete")
                        .WithMany()
                        .HasForeignKey("loginSecondAthlete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("FirstAthlete");

                    b.Navigation("Location");

                    b.Navigation("SecondAthlete");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Judge", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Judge", "login")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Organization", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Organization", "login")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationJudge", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Judge", "Judge")
                        .WithMany("OrganizationJudge")
                        .HasForeignKey("LoginJudge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Organization", "Organization")
                        .WithMany("OrganizationJudge")
                        .HasForeignKey("LoginOrganization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Judge");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationTeam", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("LoginOrganization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Team", "Team")
                        .WithMany("OrganizationTeam")
                        .HasForeignKey("NameComand")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationTrainer", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Organization", "Organization")
                        .WithMany("OrganizationTrainer")
                        .HasForeignKey("LoginOrganization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Trainer", "Trainer")
                        .WithMany("OrganizationTrainer")
                        .HasForeignKey("LoginTraine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Team", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Trainer", "Trainer")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Team", "LoginTrainer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Trainer", null)
                        .WithMany("Teams")
                        .HasForeignKey("Trainerlogin");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("DB.SportHive.Domain.TeamAthlete", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Team", "Team")
                        .WithMany("TeamAthletes")
                        .HasForeignKey("NameTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Athlete", "Athlete")
                        .WithMany("TeamAthletes")
                        .HasForeignKey("loginAthlets")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DB.SportHive.Domain.TeamMatch", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Event", "Event")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Team", "FirstTeam")
                        .WithMany()
                        .HasForeignKey("NameFirstTeam")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Team", "SecondTeam")
                        .WithMany()
                        .HasForeignKey("NameSecondTeam")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("FirstTeam");

                    b.Navigation("Location");

                    b.Navigation("SecondTeam");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Trainer", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Trainer", "login")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.UserPhoto", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.UserPhoto", "login")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Athlete", b =>
                {
                    b.Navigation("MatchesAthletes");

                    b.Navigation("TeamAthletes");
                });

            modelBuilder.Entity("DB.SportHive.Domain.ExtremeMatch", b =>
                {
                    b.Navigation("MatchesAthletes");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Judge", b =>
                {
                    b.Navigation("OrganizationJudge");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Organization", b =>
                {
                    b.Navigation("OrganizationJudge");

                    b.Navigation("OrganizationTrainer");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Team", b =>
                {
                    b.Navigation("OrganizationTeam");

                    b.Navigation("TeamAthletes");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Trainer", b =>
                {
                    b.Navigation("OrganizationTrainer");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
