// <auto-generated />
using System;
using DB.SportHive.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250413061551_addOrganizationJudge")]
    partial class addOrganizationJudge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DB.SportHive.Domain.Athlete", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataBirth");

                    b.Property<string>("FirsName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("FirsName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("LastName");

                    b.Property<string>("TypeSport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TypeSport");

                    b.HasKey("Id");

                    b.ToTable("Athlete");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Judge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataBirth");

                    b.Property<string>("FirsName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("FirsName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("LastName");

                    b.HasKey("Id");

                    b.ToTable("Judge");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Country");

                    b.Property<DateTime>("DateFoundation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateFoundation");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("NameOrganization")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("NameOrganization");

                    b.Property<string>("TypeOrganozation")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("TypeOrganozation");

                    b.HasKey("Id");

                    b.HasIndex("NameOrganization");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationJudge", b =>
                {
                    b.Property<long>("IdJudge")
                        .HasColumnType("bigint")
                        .HasColumnName("IdJudge");

                    b.Property<long>("IdOrganization")
                        .HasColumnType("bigint")
                        .HasColumnName("IdOrganization");

                    b.HasKey("IdJudge", "IdOrganization");

                    b.HasIndex("IdOrganization");

                    b.ToTable("OrganizationJudge");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Trainer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataBirth");

                    b.Property<string>("FirsName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("FirsName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("LastName");

                    b.HasKey("Id");

                    b.ToTable("Trainer");
                });

            modelBuilder.Entity("DB.SportHive.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mail");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("HashPassword");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Role");

                    b.Property<bool>("isEmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("EmailConfirmed");

                    b.Property<string>("refreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refreshToken");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("DB.SportHive.Domain.UserPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("text")
                        .HasColumnName("ProfilePhoto");

                    b.HasKey("Id");

                    b.ToTable("UserPhoto");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Athlete", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Athlete", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Judge", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Judge", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Organization", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Organization", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationJudge", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Judge", "Judge")
                        .WithMany("OrganizationJudge")
                        .HasForeignKey("IdJudge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Organization", "Organization")
                        .WithMany("OrganizationJudge")
                        .HasForeignKey("IdOrganization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Judge");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Trainer", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Trainer", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.UserPhoto", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.UserPhoto", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Judge", b =>
                {
                    b.Navigation("OrganizationJudge");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Organization", b =>
                {
                    b.Navigation("OrganizationJudge");
                });
#pragma warning restore 612, 618
        }
    }
}
