// <auto-generated />
using System;
using DB.SportHive.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250413190324_OrgTeamMigration")]
    partial class OrgTeamMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DB.SportHive.Domain.Athlete", b =>
                {
                    b.Property<string>("login")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Login");

                    b.Property<DateTime>("DataBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataBirth");

                    b.Property<string>("FirsName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("FirsName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("LastName");

                    b.Property<string>("TypeSport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TypeSport");

                    b.HasKey("login");

                    b.ToTable("Athlete");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Judge", b =>
                {
                    b.Property<string>("login")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Login");

                    b.Property<DateTime>("DataBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataBirth");

                    b.Property<string>("FirsName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("FirsName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("LastName");

                    b.HasKey("login");

                    b.ToTable("Judge");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Organization", b =>
                {
                    b.Property<string>("login")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Login");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Country");

                    b.Property<DateTime>("DateFoundation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateFoundation");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("NameOrganization")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("NameOrganization");

                    b.Property<string>("TypeOrganozation")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("TypeOrganozation");

                    b.HasKey("login");

                    b.HasIndex("NameOrganization");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationJudge", b =>
                {
                    b.Property<string>("LoginJudge")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("LoginJudge");

                    b.Property<string>("LoginOrganization")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("LoginOrganization");

                    b.HasKey("LoginJudge", "LoginOrganization");

                    b.HasIndex("LoginOrganization");

                    b.ToTable("OrganizationJudge");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationTeam", b =>
                {
                    b.Property<string>("LoginOrganization")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("LoginOrganization");

                    b.Property<string>("NameComand")
                        .HasColumnType("text")
                        .HasColumnName("NameComand");

                    b.HasKey("LoginOrganization", "NameComand");

                    b.HasIndex("NameComand");

                    b.ToTable("OrganizationTeam");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationTrainer", b =>
                {
                    b.Property<string>("LoginOrganization")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("LoginOrganization");

                    b.Property<string>("LoginTraine")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("LoginTraine");

                    b.HasKey("LoginOrganization", "LoginTraine");

                    b.HasIndex("LoginTraine");

                    b.ToTable("OrganizationTrainer");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Team", b =>
                {
                    b.Property<string>("TeamName")
                        .HasColumnType("text")
                        .HasColumnName("TeamName");

                    b.Property<string>("LoginTrainer")
                        .IsRequired()
                        .HasColumnType("character varying(40)")
                        .HasColumnName("LoginTrainer");

                    b.Property<string>("Trainerlogin")
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TypeSport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TypeSport");

                    b.HasKey("TeamName");

                    b.HasIndex("LoginTrainer")
                        .IsUnique();

                    b.HasIndex("Trainerlogin");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("DB.SportHive.Domain.TeamAthlete", b =>
                {
                    b.Property<string>("NameTeam")
                        .HasColumnType("text")
                        .HasColumnName("NameTeam");

                    b.Property<string>("loginAthlets")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("IdAthlete");

                    b.Property<string>("AthleteStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdTeam")
                        .HasColumnType("integer");

                    b.HasKey("NameTeam", "loginAthlets");

                    b.HasIndex("loginAthlets");

                    b.ToTable("TeamAthlete");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Trainer", b =>
                {
                    b.Property<string>("login")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Login");

                    b.Property<DateTime>("DataBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataBirth");

                    b.Property<string>("FirsName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("FirsName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("LastName");

                    b.HasKey("login");

                    b.ToTable("Trainer");
                });

            modelBuilder.Entity("DB.SportHive.Domain.User", b =>
                {
                    b.Property<string>("login")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("login");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mail");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("HashPassword");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Role");

                    b.Property<bool>("isEmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("EmailConfirmed");

                    b.Property<string>("refreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refreshToken");

                    b.HasKey("login");

                    b.HasIndex("login")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("DB.SportHive.Domain.UserPhoto", b =>
                {
                    b.Property<string>("login")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(40)")
                        .HasColumnName("login");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("text")
                        .HasColumnName("ProfilePhoto");

                    b.HasKey("login");

                    b.ToTable("UserPhoto");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Athlete", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Athlete", "login")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Judge", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Judge", "login")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Organization", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Organization", "login")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationJudge", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Judge", "Judge")
                        .WithMany("OrganizationJudge")
                        .HasForeignKey("LoginJudge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Organization", "Organization")
                        .WithMany("OrganizationJudge")
                        .HasForeignKey("LoginOrganization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Judge");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationTeam", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("LoginOrganization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Team", "Team")
                        .WithMany("OrganizationTeam")
                        .HasForeignKey("NameComand")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DB.SportHive.Domain.OrganizationTrainer", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Organization", "Organization")
                        .WithMany("OrganizationTrainer")
                        .HasForeignKey("LoginOrganization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Trainer", "Trainer")
                        .WithMany("OrganizationTrainer")
                        .HasForeignKey("LoginTraine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Team", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Trainer", "Trainer")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Team", "LoginTrainer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Trainer", null)
                        .WithMany("Teams")
                        .HasForeignKey("Trainerlogin");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("DB.SportHive.Domain.TeamAthlete", b =>
                {
                    b.HasOne("DB.SportHive.Domain.Team", "Team")
                        .WithMany("TeamAthletes")
                        .HasForeignKey("NameTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.SportHive.Domain.Athlete", "Athlete")
                        .WithMany("TeamAthletes")
                        .HasForeignKey("loginAthlets")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Trainer", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.Trainer", "login")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.UserPhoto", b =>
                {
                    b.HasOne("DB.SportHive.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("DB.SportHive.Domain.UserPhoto", "login")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Athlete", b =>
                {
                    b.Navigation("TeamAthletes");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Judge", b =>
                {
                    b.Navigation("OrganizationJudge");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Organization", b =>
                {
                    b.Navigation("OrganizationJudge");

                    b.Navigation("OrganizationTrainer");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Team", b =>
                {
                    b.Navigation("OrganizationTeam");

                    b.Navigation("TeamAthletes");
                });

            modelBuilder.Entity("DB.SportHive.Domain.Trainer", b =>
                {
                    b.Navigation("OrganizationTrainer");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
